---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-datasource
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server:80
      isDefault: true
      editable: false
