apiVersion: v1
kind: Pod
metadata:
  name: cpu-limited-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "1m"
      limits:
        cpu: "10m"
